### ISSUE TITLE
[FeatureRequest] Global option for 'constraintFormat'

### ISSUE THREAD

**Issue by bonanza123** [jeslago/optidef#14]
It would be great to be able to configure a global default regarding the constraint formatting.

**Comment by jeslago** [comment]
Fully agree. I will add in the next release.

**Comment by jeslago** [comment]
This has been implement in commit 56f016f89b1ac2a28cc923f60495eb08ae05b396.

I will add more featues, and update the CTAN repository with a new version.

**Comment by bonanza123** [comment]
Awesome, thanks so much for the fast implementation!
