### ISSUE TITLE
Hint regarding \protect

### ISSUE THREAD

**Issue by bonanza123** [jeslago/optidef#15]
AFAIK, it is also possible to use

```
\usepackage{etoolbox}
\robustify{\label}
```

and then skip the individual `\protect` commands

Maybe that can be added to the documentation or the package itself?

**Comment by jeslago** [comment]
Agree. I was unaware of that option, I will add it to the documentation in the next release.

**Comment by jeslago** [comment]
This was addressed in commit b568004a6abe9cd68ea377e3be60431946c500c8.

I will soon update new version to CTAN.
