### ISSUE TITLE
[FeatureRequest] Automatic labeling

### ISSUE THREAD

**Issue by bonanza123** [jeslago/optidef#16]
Just from the top of my head, I had the following idea for automatic labeling of the optimization problem:
At least for me, it is often the case that I use the following labeling scheme

- The overall problem gets e.g. `\label{eq:xxx:yyy}` where `xxx` denotes the e.g. the section or chapter and `yyy` the name of the optimization problem.
- Then the objective gets `\label{eq:xxx:yyy:obj}`
- For the contraints I see two options:
 -- Numbering ala `\label{eq:xxx:yyy:c1}`,  `\label{eq:xxx:yyy:c2}`, ...
 -- Naming ala  `\label{eq:xxx:yyy:zzz}` where `zzz` describes what that constraint is about.

I could image that an additional option e.g. to the `mini!` environment could take a name (such as `yyy` in the above case) and then the naming is done automatically in case of the numbering scheme (first option above) or the objective/constraints also get a naming option where one could provide e.g. `zzz` from the second case above.

What do you think?

**Comment by jeslago** [comment]
To be honest, I do not see a benefit of doing that. In my personal experience, nobody follows a common labelling scheme when it comes to equations. 

What I find to be common is the use of \label{eq:zzz}, where zzz can be anything. I have seen people using your style, I have also seen people ignoring the section part (the xxx in your description) but keeping the yyy part, and I have seen others directly using a different definition for each equation.

For that reason, I would rather keep this functionality out of the package.

But if you want to do that, I think it should be relatively easy. You can create a new command:

```
\DeclareDocumentCommand{\addConstraintPersonal}{m G{} G{}}{\label{youformat} \addConstraint{#1}{#2}{#3}}
```
