### ISSUE TITLE
Set of variables

### ISSUE THREAD

**Issue by AndBerna** [jeslago/optidef#21]
Hi,

First congrats for the package! Is really intutitive and easy to use.

I am trying to write an optimization model (as expected). But I have a really large set of different variables (not x1,x2... but p^{es}_{t},q^{es}_t instead). Since is completely impossible to have them under the min symbol I have created a set of variables (Gamma) instead.

After the  constraints I want to write

where    Gamma={................}

But I dont know how i can align the "where" with "minimize" and "subject to"

Thanks in advance!!

**Comment by jeslago** [comment]
Hi,

that depends on the type of alignment that you are using. How do you have aligned the constraints?

Try to add one of these and see if it works:

``` &\mathrm{where}\quad &&\gamma=```

or 

``` &\mathrm{where}\quad &\gamma=```

**Comment by AndBerna** [comment]
Hi, Thanks for the quckly answer!

I am using constraintFormat=2

Unfortunately the solution did not work. Gamma is appearing in the same line of the last constraint and the numeration is not continued.

My idea was to have:

where (aligned with min and subject to) 
Gamma (aligned with theleft hand side of the constraint)
and ={...........} with the right hand side of the constraint.

Thanks!!

**Comment by jeslago** [comment]
Can you try to add  `\\` before the commands I provided you before, i.e:

``` \\&\mathrm{where}\quad &&\gamma=```

or 

``` \\&\mathrm{where}\quad &\gamma=```

**Comment by AndBerna** [comment]
That worked perfectly!

Thanks!! =D

**Comment by jeslago** [comment]
You are welcome.
