### ISSUE TITLE
Crash when using more than z constraints

### ISSUE THREAD

**Issue by AndBerna** [jeslago/optidef#22]
Hi again, sorry for disturbing.

Im running my optimization problem in the {mini!} enviroment. But the numeration system of the whole document crashes when I exceed the z constraint (e.g 4.36z). Is there any way to have more than 24 numbered constraints?

Thanks in advance

**Comment by jeslago** [comment]
Can you try to add the following to your document preamble:

```
\usepackage{alphalph}
\newcommand{\alphalphval}[1]{\alphalph{\value{#1}}}

\AtBeginDocument{%
	\AtBeginEnvironment{subequations}{%
		\let\alph\alphalphval%
	}
}
```

Does this work?

**Comment by AndBerna** [comment]
Hi, it did solve the issue, but partially.

It works perfectly when the equation fits in a single line. 
But my set of constraints is so big that it does not fit even in one line. I am writting 

`\\&\mathrm{where}\quad &&\Gamma=\left.\{ p^{hp}_{t,n},p^{b}_t,p^{es}_{t,ch},p^{es}_{t,dis},p^{es-hp}_{t,n},p^{es-b}_t,q^{hp}_{t,n},q^b_t,q^{hp-hs}_{t,n},q^{b-hs}_{t},...
\\ & && ... \ SOC^{hs}_{t},SOC^{es}_t,u^{hp}_{t,n},u^{hp}_{t,ON},u^{hp}_{t,OFF},u^{hs}_t\right.\}\label{eq:scenario_2_variables}` 

When I do this before the numeration appears the word "subequation" in cursives. I tried to use the enviroment split but it did not work either.

Thanks again





What should I do in this case?

Thanks again!

**Comment by jeslago** [comment]
~~You can use the standard `\addConstraint` command for breaking the constraint, and use `\nonumber` for removing the reference~~. Alternative, you can simply use the `\\` command to manually split the constraint as you did to include the `where Gamma` part.

**Comment by AndBerna** [comment]
Hi, 

Second alternative worked perfectly. Thanks!

However, just to inform you If I am using \addConstraint after the "where" the "subject to" appears again.

 Thanks for all and your time! =D

**Comment by jeslago** [comment]
Yes, it makes sense that it does that. The reason being that the package is not originally intended for adding regular text between the constraints. In any case, you could in principle use the `\addConstraint` command (even for the `where Gamma` part you could in theory use it with `\addConstraint`) and add regular text. Then, subject to would never appear again.
