### ISSUE TITLE
Overlapping second and first alignment with constraint format 2

### ISSUE THREAD

**Issue by arogeau** [jeslago/optidef#25]
Hi,

I'm having an issue when trying to use extra alignments with format 2. They go after all the longest equations (in my case, the two first constraints). Do these extra alignments just work with the format 0 ?

WRE:
```
\documentclass{article}
\usepackage{optidef}
\begin{document}
\begin{mini*}[2]
{X}{\mathrm{OBJ}(X)}{}{}
\addConstraint{F_{1}(X)}{\ge \mathrm{\Delta }_{1} F_{1}(X_0)}
\addConstraint{F_{2}(X)}{\ge \mathrm{\Delta }_{2} F_{2}(X_0)}
\addConstraint{\sum_{j\in R}{x_{i,j}}}{=1,\quad}{\forall i\in P}
\addConstraint{\sum_{k\in H}{y_{k}}}{=1}
\addConstraint{x_{i,j}}{\in \{0,1\},\quad}{\forall i\in P, j\in R}
\addConstraint{y_{k}}{\in \{0,1\},\quad}{\forall k\in H}
\end{mini*}
\end{document}
```

Thanks

**Comment by bonanza123** [comment]
please provide a full MWE.

**Comment by arogeau** [comment]
It is working, but I don't know how to format it

**Comment by bonanza123** [comment]
If you want the help from others, you should try to make it as easy as possible for them to help you.

**Comment by bonanza123** [comment]
Its not compiling on my machine, I am getting a lot of `! Missing \endgroup inserted.` Please provide a MWE. see https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-example-what-is-that

**Comment by arogeau** [comment]
Sorry I though it was obvious I was talking about the "optidef" package in this optidef project.

**Comment by bonanza123** [comment]
It is obvious, I am sorry, I give up at this point.
What does not seem to be obvious is the concept of MWEs.

**Comment by arogeau** [comment]
Did you see that I modified my original post ?
Still not working ?

**Comment by jeslago** [comment]
Where do you want these constraints to be? If you use the alignment 2, all the equations will be aligned to the left, which destroys the first alignment point. The second alignment point it is still working, so anything that you write as a third parameter will be aligned in this second alignment point.

If you don't want the second alignment point, then simply don't use it, e.g.


```
\documentclass{article}
\usepackage{optidef}
\begin{document}
\begin{mini*}[2]
{X}{\mathrm{OBJ}(X)}{}{}
\addConstraint{F_{1}(X)}{\ge \mathrm{\Delta }_{1} F_{1}(X_0)}
\addConstraint{F_{2}(X)}{\ge \mathrm{\Delta }_{2} F_{2}(X_0)}
\addConstraint{\sum_{j\in R}{x_{i,j}}}{=1,\quad\forall i\in P}
\addConstraint{\sum_{k\in H}{y_{k}}}{=1}
\addConstraint{x_{i,j}}{\in \{0,1\},\quad\forall i\in P, j\in R}
\addConstraint{y_{k}}{\in \{0,1\},\quad\forall k\in H}
\end{mini*}
\end{document}
```

If what you want is to have to second alignment point before the end of the longest constraints, then you need to make a hack. You could do something like this:

```
\documentclass{article}
\usepackage[nocomma]{optidef}
\begin{document}
\begin{mini*}[2]
{X}{\mathrm{OBJ}(X)}{}{}
\addConstraint{F_{1}(X)}{\ge \mathrm{\Delta }_{1} F_{1}(X_0)\span\span}
\addConstraint{F_{2}(X)}{\ge \mathrm{\Delta }_{2} F_{2}(X_0)\span\span}
\addConstraint{\sum_{j\in R}{x_{i,j}}}{=1,\quad}{\forall i\in P}
\addConstraint{\sum_{k\in H}{y_{k}}}{=1}
\addConstraint{x_{i,j}}{\in \{0,1\},\quad}{\forall i\in P, j\in R}
\addConstraint{y_{k}}{\in \{0,1\},\quad}{\forall k\in H}
\end{mini*}
\end{document}
```

Keep in mind that now you need to add the commas in the objective yourself.

**Comment by arogeau** [comment]
Well, this second option does satisfy me perfectly !
Tnak you so much for you fast answer !

**Comment by jeslago** [comment]
I edit the title as it is not an issue but more of a request. The behavior that you get it is the behavior that it is expected of the package.

I am glad that I could help.
