### ISSUE TITLE
use optidef in 2 column mode

### ISSUE THREAD

**Issue by Matthiassss** [jeslago/optidef#27]
Hello,

I want to use optidef in 2 column mode, but the optimisation problem should spread over both columns. How does that work? Is there anything similar to \begin{table*}. Obvioulsy \begin{mini*} does bot work.

Thanks!
Matthias

**Comment by jeslago** [comment]
Can you try the `widetext` environment? See this [answer](https://tex.stackexchange.com/questions/26707/one-column-equation-in-twocolumn-document-class)

**Comment by Matthiassss** [comment]
Thanks for the hint. widetext did not work, but while reading on widetext I found this and it works.
\usepackage{cuted}
\begin{strip}
...
\end{strip}
