### ISSUE TITLE
Counter too large

### ISSUE THREAD

**Issue by Yishun-Wang** [jeslago/optidef#28]
Hi, 
I have more than 26 constraints in my model and I have used {mini!} environment. If I add the 27th constraint in, latex will not compile and have the error ‘Counter too large'. I find that the labeling of constraints cannot go more than z. For instacne, the labeling  can go from 3a-3z but not more. How to deal with this? The follwoing is my code. (it will not compile) 

%\begin{mini!}
%	{X_{ij}^t,P_{ij}^t, I_{nk}^t }{\overline{Z} \protect\label{eq:ObjectiveExample1}}
%	{\label{MILP}}{}
%	\addConstraint{     \overline{Z} \geq X_{ij}^tt,\forall l _{ij} \in L_R,  \forall t\in T \protect \label{c18} }
%	\addConstraint{B^t_i=\beta E_i^t-\sum_{l_{ij}\in L_T} P_{ij}^tX_{ij}^t, \forall i \in V_R, t=1 \protect\label{c1}}
%	\addConstraint{B^{t+1}_i = B_i^t +\beta E_i^{t+1} - \sum_{l_{ij}\in L_T} P^{t+1}_{ij}X^{t+1}_{ij},} { \forall i \in V_R, t=1,2,3,\dots,T-1 \protect \label{c2}}
%		\addConstraint{B_n^t= Y_n^t - P_{ni}^t X_{ni}^t, \forall n \in V_E, t =1 \protect\label{c4}    }
%		\addConstraint{B_n^{t+1} = B_n^t +Y_n^{t+1}-P_{ni}^{t+1}X_{ni}^{t+1} , \forall n \in V_E, \forall  l_{ni} \in L_N, t= 1,2,3,\dots T-1 \protect\label {c5}}
%		\addConstraint{ P_{ij}^tX_{ij}^t  +P_{i\hat{e}}^t X_{i\hat{e}}^t \leq B_{max}, \forall i \in V_R, \forall l_{ij} \in L_T, \forall  t\in T\label{c3}}
%		\addConstraint{ P_{ni}^tX_{ni}^t \leq \hat{B}_{max} ,  \forall n \in V_E, \forall t \in T\protect \label{c15} }
%			\addConstraint{  \sum\limits_{t=1}^T X_{xy}^t \geq 1, \forall l_{xy} \in L_R \protect\label{c6}}
%			\addConstraint{  \sum\limits_{l_{yu}\in L_T}X_{yu}^t, \forall y \in V_R,\forall t\in T\protect\label{c7} }
%			\addConstraint{\gamma( Q^t_{xy}+N_0) \geq \Phi_1(X_{xy}^t-1),\protect\label{c8}}
%			\addConstraint{	Q^t_{xy}=\sum_{l_{ij}\in L\setminus l_{xy}}G_{iy}P_{ij}^{t}X_{ij}^t, \forall l_{xy}\in L_R, \forall t\in T\protect   \label{c8s}		}
%			\addConstraint{0\leq P_{ij}^t, t= 1,2,\dots T, \forall l_{ij} \in L_T\protect  \label{c9}}
%			\addConstraint{0\leq P_{ni}^t , \forall t\in T, \forall l_{ni} \in L_N\protect \label{c10} }
%			\addConstraint{0\leq B_i^t\leq B_{max} , \forall i \in V_R,  \forall t\in T\protect  \label{c11}} 
%			\addConstraint{0 \leq B_n^t \leq \hat{B}_{max} , \forall n \in V_E,\forall t\in T   \protect \label{c12} }
%			\addConstraint{S_i^t \geq 0, \forall n \in V_R, \forall t \in T \protect \label{c11s}}
%			\addConstraint{S_n^t \geq 0, \forall n \in V_E, \forall t \in T\protect \label{c12s}}
%			\addConstraint{ Y_n^t \geq 0,  \forall n \in V_E, t= 1,2, 3\dots T\protect  \label{c13}}
%			\addConstraint{     Y_n^t \leq	M_{nk}^t,\forall n \in V_E,\forall t\in T  \protect \label{c14}}
%			\displaybreak
%			\addConstraint{  (1) \geq Y_n^t, \forall n \in V_E, \forall l_{ni}\in L_N, \forall t\in T\protect \label{c16 }}
%			\addConstraint{Y_n\geq  ,\forall n \in V_E,\forall t\in T\protect \label{c17}}
%			\addConstraint{ k= 1, \forall n \in V_E, \forall t \in T\protect \label{c24}}
%			\addConstraint{   I \leq M_{nt}^k\leq I_{nt}^k P_U^k, \forall t\in T,k = {1,2,3,\dots, K}, \forall n \in V_E \protect \label{c19}  }		
%			\addConstraint{ k\leq I_{nt}^k \Phi_4, \forall t\in T, k = {1,2,3,\dots, K}, \forall n \in V_E\protect \label{c20}}		
%			\addConstraint{ k \geq 0 , \forall t\in T, k = {1,2,3,\dots, K}, \forall n \in V_E\protect\label{c21}}	
%			\addConstraint{abc}
%\end{mini!}

**Comment by jeslago** [comment]
Please, check the closed issues before opening a new one. This has been answered in #22

**Comment by Yishun-Wang** [comment]
Thank you! My mistake, problem solved!
