### ISSUE TITLE
Paragraph indent after the mini, maxi, etc. environments

### ISSUE THREAD

**Issue by sudeshkagrawal** [jeslago/optidef#32]
Even when I don't have an empty line after those environments, I get an indentation. I am not sure if this is a paragraph indentation (because my paragraph indentations were of different length) or a bug?

If it were a paragraph indentation, then it should presumably not occur if I follow the advice at https://tex.stackexchange.com/a/566.

**Comment by sudeshkagrawal** [comment]
What I am currently doing to get the desired result is forcing a new paragraph with an empty line and using "\noindent" at the start of that paragraph

**Comment by jeslago** [comment]
What version of the package are you using? Can you provide an example of the problem?

**Comment by jeslago** [comment]
I close the issue due to inactivity

**Comment by sudeshkagrawal** [comment]
I used Overleaf, and I am not sure how to find the package version in Overleaf.

**Comment by HandsomeManKris** [comment]
I also have this problem....... It is closed????

**Comment by jeslago** [comment]
I need a minimum working example. If you are using overleaf, you can try to download the optidef.sty file from github and add it to the overleaf project. That should solve the issue if it is related to an outdated package (in the past the package had indentation issues).

**Comment by jeslago** [comment]
I am closing this issue do to inactivity. If somebody reopens it, please provide a minimum working example.
