### ISSUE TITLE
translate minimize/subject to

### ISSUE THREAD

**Issue by RAlbieri** [jeslago/optidef#35]
I would like to translate to portuguese:
"minimize" -> "minimizar" 
"subject to"-> "sujeito a"
Is it possible to redefine easily?

Thanks

**Comment by jeslago** [comment]
You could redefine more or less easily, but it would take a bit of time. It is in my todo list to implement a flexible environment where minimize and subject to can be modified.

At the moment, a quick fix is to do a search and replace. Dowload the optidef.sty file to your main folder. Replace all all the occurrences of `minimize` by `minimizar` and all the occurrences of `subject~to` by `suxeito~a`.

**Comment by RAlbieri** [comment]
Thanks!

It worked perfectly.

**Comment by zhtaihao** [comment]
Hi, has there been any progress on this issue? I haven't seen anything relevant in the user documentation.
I think many other packages parse the language defined in \usepackage[british]{babel} for example. In my case, I'd like the spelling of "minimize" to adapt to british spelling "minimise".

I'll work with the quick fix you proposed for now, it would be nice to see this as an automatic feature.

**Comment by jeslago** [comment]
Hi,

I currently don't have time to maintain or update this library. I would appreciate it if anybody from the community could take up and maintain it.

**Comment by caomem** [comment]
To just use it fast in portuguese, go to your main folder and run in your terminal
```wget https://raw.githubusercontent.com/caomem/optidef/master/optidef.sty```

It already have the replaces. If you will replace to another language, don't forget to replace the `s.t.` too.
