### ISSUE TITLE
Is it possible within the package to align everything on the left margin of a report?

### ISSUE THREAD

**Issue by BenMobility** [jeslago/optidef#38]
![image](https://user-images.githubusercontent.com/71120690/95650564-af9c2800-0ae4-11eb-8ea2-fc46f23ee654.png)

**Comment by jeslago** [comment]
Hi, 

before importing optidef, you can add the following line:

```\usepackage[fleqn]{amsmath}```

However, this would change the alignment of all equations. I am not sure how you could do it for a single equation. Optidef is based on the amsmath package of latex, so if you find out how to change the alignment for a single amsmath equation, perhaps the same behaviour can be imported to optidef.

**Comment by BenMobility** [comment]
Ok thanks! I tried to change the alignment for only one equation, but it didn't work out like a single amsmath equation. 
But your answer is enough for me now 👍

**Comment by jeslago** [comment]
Can you provide a minimal working example of a situation that works for the align environment of amsmath and it does not for optidef?

**Comment by BenMobility** [comment]
Sure! Here is the working version(simplified)
```
\documentclass[helv, dvipsnames]{apa7}
\usepackage[fleqn]{amsmath} 
\usepackage[nocomma]{optidef}
\begin{document}

\[
f(v) = (0.0036\cdot v^2 - 0.1015 \cdot v + 0.8848 
\]

\begin{mini!}[1]
{}{\sum_{v\in V}\sum_{h\in H_v}\sum_{e\in L_h}\underbrace{c_e^vx_e}_{\text{total vessel cost}}+\sum_{c \in C}\underbrace{[\underbrace{c_m^my_c}_{\text{misconnection cost}}+\underbrace{c_c^do_c}_{\text{delay cost}}]}_{\text{containers}}}{}{}
	\addConstraint{\sum_{e\in L_h}x_e+z_h}{=1}{\quad \forall v \in V, h \in H_v}
\end{mini!}
\end{document}
```
My goal is to only align the optidef equation here and not the first one.

I tried this 
```
\documentclass[helv, dvipsnames]{apa7}
\usepackage{amsmath} 
\usepackage[nocomma]{optidef}
\begin{document}

\[
f(v) = (0.0036\cdot v^2 - 0.1015 \cdot v + 0.8848 
\]
\begin{flalign}
    \begin{mini!}[1]
        {}{\sum_{v\in V}\sum_{h\in H_v}\sum_{e\in L_h}\underbrace{c_e^vx_e}_{\text{total vessel cost}}+\sum_{c \in C}\underbrace{[\underbrace{c_m^my_c}_{\text{misconnection cost}}+\underbrace{c_c^do_c}_{\text{delay cost}}]}_{\text{containers}}}{}{}
    	\addConstraint{\sum_{e\in L_h}x_e+z_h}{=1}{\quad \forall v \in V, h \in H_v}
    \end{mini!}
\end{flalign}

\end{document}
```
But It didn't work

**Comment by BenMobility** [comment]
Feel free to ask me to provide you more info or less, whatever suits you better

**Comment by jeslago** [comment]
The problem is that you can't just add `flalign` around.

The optidef package uses the environment align underneath. So, something like:

```
\begin{mini}{x}{f(x)}{}{}
\end{mini}
```

Is internally expanded as:

```
\begin{align}
\underset{\displaystyle x}{\mathrm{minimize}}& \quad f(x)
\end{align}
```

One could get the same equation aligned to the left by using:

```
\begin{flalign}
\underset{\displaystyle x}{\mathrm{minimize}}& \quad f(x)
\end{flalign}
```
But not

```
\begin{flalign}
\begin{align}
\underset{\displaystyle x}{\mathrm{minimize}}& \quad f(x)
\end{align}
```

that is what you are effectively doing when adding `\flalign` around the `mini` environment. If you only need the left alignment for the optimization problems, a possible solution is to download the `optidef.sty` package and modify all the `align` instances by `flalign`. That however will change the behaviour of all optimization problems.

We could add this as a feature to the package in the future, but I can't say when.

**Comment by BenMobility** [comment]
Ok, thanks for the detailed answer!! Much appreciated! :)
