### ISSUE TITLE
Write constraints separately

### ISSUE THREAD

**Issue by jonmtz** [jeslago/optidef#40]
Hi there!

I would like to know if there is a way to write just some constraints without having to add an objective function (and without the text: "subject to").

This could be useful for example for cases in which you explain the constraints separately in an article (for adding text and explanations from one constraint to another).

Thank you and congrats for the library, I find it so useful! :)

**Comment by jeslago** [comment]
Such a feature wouldn't be hard (I guess) to implement, but i am not sure how it would be useful. 

You are describing standard standalone alignment, right?  In that case  the `alignat` or `align` environments can do the job. Are you thinking of any different use case?

**Comment by jonmtz** [comment]
Thank you for your answer @jeslago. 
The idea is to be able to align the usually used three terms (constraint, \forall{whatever} and the equation number) as it is done in the optidef package.
I am pretty new writing equations in LateX, so that may also be possible to be done with `alignat` or `align`, but I am not sure about it.
Regards,

**Comment by jeslago** [comment]
For those cases you can use `alignat` and `subequations` directly

```
\begin{subequations}
\begin{alignat}{3}
f(x_k) &= g(x_k), \quad &&\forall k=1,....,N\\
h(y_k) + m(x_k) &= p(x_k) - d(y_k), \quad &&\forall k=1,....,N \\
\end{alignat}
\end{subequations}
```

The number 3 indicates the number of alignment points. If you use one alignment `&` for the first alignment point and then `&&` afterwards everything would look as with optidef. But you can play with `&` and `&&` to tweak the alignments and add more alignments as you wish.

**Comment by jonmtz** [comment]
Thank you very much @jeslago :)
