### ISSUE TITLE
Include inf / sup, infimum / supremum

### ISSUE THREAD

**Issue by janoellerich** [jeslago/optidef#46]
Dear Jeslago,

Is it possible to include the options inf / sup, infimum / supremum? I am currently working on an optimization problem where an infimum is required. Thank you very much in advance and kind Regards. :)

Jan

**Comment by jeslago** [comment]
Hi,

You can do so with the `customopti` environment. See this open issue https://github.com/jeslago/optidef/issues/39. It is a feature I implemented 2 years ago, but never "officially" launched.

I will try to work on the coming months to make it official. But for now, you can download the sty file in your folder and use it.

**Comment by janoellerich** [comment]
Great, thank you, I will try it! :)
