### ISSUE TITLE
[bug] Extra space after \begin{mini} environment

### ISSUE THREAD

**Issue by roversch** [jeslago/optidef#6]
After the minimize environment, I get an extra space at the beginning of the text following the environment, for example 

```
\begin{mini!}
    {w \in \R^n}
    {f(w)}
    {\label{eq:convex}}
    {}
    \addConstraint{C w}{= \overline{c}}
    \addConstraint{w}{\in \Omega,}
\end{mini!}
where we define ...
```

which renders with an extra space,
<img width="398" alt="screen shot 2016-10-19 at 13 27 58" src="https://cloud.githubusercontent.com/assets/1436556/19517186/f7242e92-95ff-11e6-84bd-2b1dd6110adf.png">
when it should not.

**Comment by jeslago** [comment]
Are you using the IFAC template or is it a different template?

I have observed the same issue with the IFAC template, but I did not have it when I wrote Moritz book or my own thesis.

I have to further look into it, because I thought it was the IFAC template.

**Comment by roversch** [comment]
Yes, I use the IFAC template. Note that I don't get a space in this
template after e.g. the 'equation' environment.

**Comment by jeslago** [comment]
The thing is that mini! uses subequations together with alignat. Can you try this in the IFAC template? I you can't, I can try it myself tonight.

```
\begin{subequations}
\begin{alignat}{2}
x&=y+1\\ 
yx&=5
\end{alignat}
\end{subequations}
```

If the above produces the same problem, there is nothing I can do. I think in my paper I solved it manually (I have to look exactly how I did it).

**Comment by roversch** [comment]
No, the snippet you gave me does not have the problem, the text directly
after the 'subequations' environment is aligned all the way to the left.

**Comment by jeslago** [comment]
I think I fixed. Can you download the latest package version and try it out? It works now with my paper.

**Comment by roversch** [comment]
Yes, this seems to have fixed it.

Thanks!
