### ISSUE TITLE
Missing extra alignment for first constraint with constraint format 3

### ISSUE THREAD

**Issue by nasobem** [jeslago/optidef#7]
Hi,

I've noticed a small bug with the extra alignment for the first constraint if constraint format 3 is used.
When I switch from constraint format 2 to 3 the content of the extra alignment brackets does vanish, but only for the first constraint added to the program. I've attached two screenshots to illustrate the problem. Maybe you've got any idea, what might be the problem there?
I'm using optidef 2016/10/22 - version=2.3
Thanks for your help!

![capture2](https://cloud.githubusercontent.com/assets/26159024/26342083/33c04ff2-3fc9-11e7-9442-8be0c1749ba1.PNG)
![capture](https://cloud.githubusercontent.com/assets/26159024/26342084/33c3bdfe-3fc9-11e7-9778-8af46e92571c.PNG)

**Comment by jeslago** [comment]
Hi,

could you please send me a latex code so I can reproduce it in my computer?

Thanks.

**Comment by jeslago** [comment]
FYI: I tried to reproduce the error in my computer and everything works fine. Send me your code please.

**Comment by nasobem** [comment]
Hi,
here's an MWE.
Thanks for your quick respond!
[optidef_test.tex.txt](https://github.com/jeslago/optidef/files/1021305/optidef_test.tex.txt)

**Comment by jeslago** [comment]
I think I have spotted a bug. 

Could you please try the use the updated optidef library and let me know if it works? Just download the optidef.sty file from the repository and put it in the same directory as your latex code.

**Comment by nasobem** [comment]
Works like a charm.
Thank you, Sir! :)

**Comment by jeslago** [comment]
Glad to hear that.
